// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_get_logs from "./routes/api/get_logs.ts";
import * as $api_get_result from "./routes/api/get_result.ts";
import * as $api_get_status from "./routes/api/get_status.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_start_task from "./routes/api/start_task.ts";
import * as $index from "./routes/index.tsx";
import * as $taskManager from "./islands/taskManager.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/get_logs.ts": $api_get_logs,
    "./routes/api/get_result.ts": $api_get_result,
    "./routes/api/get_status.ts": $api_get_status,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/start_task.ts": $api_start_task,
    "./routes/index.tsx": $index,
  },
  islands: {
    "./islands/taskManager.tsx": $taskManager,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
